[project]
name = "adas-capstone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.13"
dependencies = [
    "bcrypt==4.0.1",
    "fastapi[standard]>=0.136.1",
    "gputil>=1.4.0",
    "opencv-python>=4.13.0.92",
    "passlib[bcrypt]>=1.7.4",
    "psutil>=7.2.2",
    "pyjwt>=2.12.1",
    "pytest>=9.0.3",
    "python-multipart>=0.0.26",
    "requests>=2.33.1",
    "sqlmodel>=0.0.38",
    "tensorrt>=10.16.1.11",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
]
[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }

[tool.pytest.ini_options]
testpaths = ["backend/tests"]
cache_dir = "backend/.pytest_cache"
