"""Pydantic request/response models. SQLModel table definitions live in
app.models, not here — see 02_PKG_foundation.md Step 3."""

from app.schemas.analytics import (
    DashboardAnalyticsResponse,
    DashboardKpis,
    LocationFrequency,
    PeakAccidentHour,
    PerformanceAnalyticsResponse,
    PerformanceCameraRow,
    PerformanceGlobalKpis,
)
from app.schemas.audit import AuditLogListResponse, AuditLogRead
from app.schemas.auth import LoginResponse
from app.schemas.camera import (
    AiBreakdown,
    CameraBreakdowns,
    CameraCreate,
    CameraDetailRead,
    CameraKpis,
    CameraListResponse,
    CameraRead,
    CameraUpdate,
    ConnectionBreakdown,
)
from app.schemas.common import ApiError, default_error_code, validate_password_strength
from app.schemas.detection import (
    AlertSnoozeRequest,
    DetectionLogCreateV2,
    DetectionLogListResponse,
    DetectionLogRead,
)
from app.schemas.events import (
    AlertStatusUpdateData,
    CameraStatusUpdateData,
    ConnectionReadyData,
    EventEnvelope,
    EventType,
    IncidentPayload,
    MaintenanceNoticeData,
    ReAlarmData,
    SnoozeActivatedData,
    make_event,
)
from app.schemas.exports import (
    ExportJobCreate,
    ExportJobCreateResponse,
    ExportJobListResponse,
    ExportJobRead,
    RetrainingExportRequest,
)
from app.schemas.health import (
    GpuRead,
    HealthHistoryPoint,
    HealthHistoryResponse,
    HealthWarning,
    SysHealthHourlyRead,
    SysHealthLive,
    SysHealthRawRead,
)
from app.schemas.help import (
    HelpArticleDetail,
    HelpArticleListResponse,
    HelpArticleSummary,
)
from app.schemas.maintenance import (
    BackupListResponse,
    BackupRead,
    BackupTriggerResponse,
    RestoreRequestIn,
    RestoreStateRead,
    RestoreStepRead,
    RestoreTriggerResponse,
)
from app.schemas.settings import AlarmSettingsRead, AlarmSettingsUpdate
from app.schemas.user import (
    UserAdminUpdate,
    UserCreate,
    UserListResponse,
    UserOperatorUpdate,
    UserRead,
    UserResetPassword,
    UserUpdatePassword,
)

__all__ = [
    "AiBreakdown",
    "AlarmSettingsRead",
    "AlarmSettingsUpdate",
    "AlertSnoozeRequest",
    "AlertStatusUpdateData",
    "ApiError",
    "AuditLogListResponse",
    "AuditLogRead",
    "BackupListResponse",
    "BackupRead",
    "BackupTriggerResponse",
    "CameraBreakdowns",
    "CameraCreate",
    "CameraDetailRead",
    "CameraKpis",
    "CameraListResponse",
    "CameraRead",
    "CameraStatusUpdateData",
    "CameraUpdate",
    "ConnectionBreakdown",
    "ConnectionReadyData",
    "DashboardAnalyticsResponse",
    "DashboardKpis",
    "DetectionLogListResponse",
    "DetectionLogRead",
    "default_error_code",
    "DetectionLogCreateV2",
    "EventEnvelope",
    "EventType",
    "ExportJobCreate",
    "ExportJobCreateResponse",
    "ExportJobListResponse",
    "ExportJobRead",
    "GpuRead",
    "HealthHistoryPoint",
    "HealthHistoryResponse",
    "HealthWarning",
    "HelpArticleDetail",
    "HelpArticleListResponse",
    "HelpArticleSummary",
    "IncidentPayload",
    "LocationFrequency",
    "LoginResponse",
    "MaintenanceNoticeData",
    "PeakAccidentHour",
    "PerformanceAnalyticsResponse",
    "PerformanceCameraRow",
    "PerformanceGlobalKpis",
    "RestoreRequestIn",
    "RestoreStateRead",
    "RestoreStepRead",
    "RestoreTriggerResponse",
    "RetrainingExportRequest",
    "make_event",
    "ReAlarmData",
    "SnoozeActivatedData",
    "SysHealthHourlyRead",
    "SysHealthLive",
    "SysHealthRawRead",
    "UserAdminUpdate",
    "UserCreate",
    "UserListResponse",
    "UserOperatorUpdate",
    "UserRead",
    "UserResetPassword",
    "UserUpdatePassword",
    "validate_password_strength",
]
