"""Regenerate paper_sync/TRACKER.md from the findings queue.

TRACKER.md is generated, never hand-edited: the findings files are the only
source, so the summary cannot drift from what it summarises.

Deliberately stdlib-only. This runs under Claude Code, Codex and Antigravity
alike, and a teammate who has not run `uv sync` still needs it to work:

    uv run python paper_sync/build_tracker.py

Frontmatter is flat `key: value` by construction (see PROCEDURE.md's template),
so it is parsed directly rather than pulling in PyYAML for six string fields.
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
FINDINGS = HERE / "findings"
TRACKER = HERE / "TRACKER.md"

# Order matters — it mirrors the live ADAS_Paper_Audit_Tracker sheet, which has
# no `Action Taken` and no `Deadline` column.
COLUMNS = [
    ("section", "Section / Chapter"),
    ("page/s", "Page Number"),
    ("required_revision", "Required Revision"),
    ("notes", "Notes"),
    ("status", "Status"),
    ("assigned_to", "Assigned to"),
]

HEADER = """<!-- Generated by paper_sync/build_tracker.py. Do not edit by hand. -->

# Paper audit tracker (local queue)

Built from `paper_sync/findings/`, which is where every finding is written. The
live `ADAS_Paper_Audit_Tracker` sheet is authoritative; this file makes the same
rows reviewable and diffable in the repo.

Rows marked **unsynced** have not been copied into the sheet by anyone yet.
"""

# A finding may cite several pages, so the key is `page/s`. Files written before
# that rename use `page`; read both rather than silently emitting a blank cell.
ALIASES = {"page/s": ("page/s", "page")}


def field(fields: dict[str, str], key: str) -> str:
    """Frontmatter value for a column, trying that column's older key names."""
    for candidate in ALIASES.get(key, (key,)):
        if candidate in fields:
            return fields[candidate]
    return ""


def parse_frontmatter(path: Path) -> dict[str, str] | None:
    """Return the frontmatter of a findings file, or None if it has none."""
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    fields: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            return fields
        key, sep, value = line.partition(":")
        if sep:
            fields[key.strip()] = value.strip().strip("\"'")
    # No closing delimiter: malformed rather than empty, so say so loudly.
    return None


def escape(value: str) -> str:
    """Keep a stray pipe in a summary from splitting the Markdown table."""
    return value.replace("|", "\\|")


def main() -> int:
    findings = sorted(FINDINGS.glob("*.md")) if FINDINGS.is_dir() else []
    findings = [p for p in findings if p.name != "README.md"]

    rows: list[tuple[Path, dict[str, str]]] = []
    malformed: list[Path] = []
    for path in findings:
        fields = parse_frontmatter(path)
        if fields is None:
            malformed.append(path)
        else:
            rows.append((path, fields))

    out = [HEADER]

    if not rows:
        out.append("\n_No findings queued._\n")
    else:
        unsynced = sum(1 for _, f in rows if f.get("synced", "false") == "false")
        out.append(f"\n{len(rows)} finding(s), {unsynced} unsynced.\n\n")
        out.append(
            "| " + " | ".join(label for _, label in COLUMNS) + " | Synced | Source |\n"
        )
        out.append("| " + " | ".join("---" for _ in COLUMNS) + " | --- | --- |\n")
        for path, fields in rows:
            cells = [escape(field(fields, key)) for key, _ in COLUMNS]
            synced = fields.get("synced", "false")
            cells.append("no" if synced == "false" else escape(synced))
            cells.append(f"[{path.name}](findings/{path.name})")
            out.append("| " + " | ".join(cells) + " |\n")

    if malformed:
        out.append("\n## Malformed\n\nThese files have no parsable frontmatter:\n\n")
        out.extend(f"- `{p.name}`\n" for p in malformed)

    TRACKER.write_text("".join(out), encoding="utf-8")
    print(f"Wrote {TRACKER.relative_to(HERE.parent)} ({len(rows)} finding(s))")
    if malformed:
        print(
            f"WARNING: {len(malformed)} file(s) had unparsable frontmatter",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
